use_frameworks!

platform :ios, '9.0'

target 'MTKVOManagerComponent_Example' do
  pod 'MTKVOManagerComponent', :path => '../'

  target 'MTKVOManagerComponent_Tests' do
    inherit! :search_paths

    
  end
end
